name: aakjaer.co
description: Private website for Daniel Aakjær Sørensen
author:
  name: Daniel Aakjær Sørensen
  email: contact@aakjaer.co

sass:
  sass_dir: _scss

permalink: date

# Markdown library
markdown: redcarpet
#   extensions: ['fenced_code_blocks', 'smart']

highlighter: pygment
