name: aakjaer.co
description: Private website for Daniel Aakjær Sørensen
author:
  name: Daniel Aakjær Sørensen
  email: contact@aakjaer.co

host: 0.0.0.0

sass:
  sass_dir: _scss

permalink: date

highlighter: rouge


gems:
  - jekyll-sitemap
